### ISSUE TITLE
[Feature Request] Add unit tests

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dpdata#170]
**Summary**

Add unit tests for current modules. Some of them do not have packages installed.

**Detailed Description**

According to [Codecov](https://codecov.io/gh/deepmodeling/dpdata/tree/devel/dpdata), the following codes doesn't have unit tests.
system:
- [ ] `System.__str__`
- [ ] `System.dump`
- [ ] `System.extend`
- [x] `System.predict` (#277)
- [ ] `LabeledSystem.__str__`
- [x] `MultiSystems.__len__` (fixed by #172)
- [ ] `MultiSystems.__repr__`
- [x] `MultiSystems.__str__` (fixed by #172)
- [ ] `MultiSystems.from_dir`
- [x] `MultiSystems.get_nframes` (fixed by #172)
- [ ] `MultiSystems.predict`
- [ ] `MultiSystems.pick_atom_idx`

formats:
- [ ] `amber/md`: `from_system`
- [x] `ase/structure`: `to_system` (fixed by #171)
- [ ] `ase/structure`: `to_labeled_system`
- [x] `pymatgen/structure`: `to_system` (fixed by #171)
- [x] `pymatgen/structure`: `to_labeled_system` (fixed by #171)
- [ ] `mol`: `to_bond_order_system`
- [x] `sdf`: `to_bond_order_system` (#188)
- [ ] `siesta/output`: `from_system`
- [ ] `siesta/aimd_output`: `from_system`
